--- a/Makefile
+++ b/Makefile
@@ -20,13 +20,14 @@
 	$(CC) $(CFLAGS) -DINI_FILE=\"${INI_Q}\" maxqi.c -o maxqi
 
 install: ${ALL} ${srcdir}/data/*
+	install -d -m0755 $(DESTDIR)/usr/games
 	cp -u ${srcdir}/fairymax $(DESTDIR)/usr/games
 	cp -u ${srcdir}/shamax $(DESTDIR)/usr/games
 	cp -u ${srcdir}/maxqi $(DESTDIR)/usr/games
 	install -d -m0755 $(DESTDIR)/usr/share/games/fairymax
 	cp -u ${srcdir}/data/* $(DESTDIR)/usr/share/games/fairymax
-	install -d -m0755 $(DESTDIR)/usr/share/man/man6
-	cp -u ${srcdir}/fairymax.6.gz $(DESTDIR)/usr/share/man/man6
+	install -d -m0755 $(DESTDIR)/usr/man/man6
+	cp -u ${srcdir}/fairymax.6.gz $(DESTDIR)/usr/man/man6
 
 fairymax.6.gz: fairymax.pod
 	pod2man -s 6 fairymax.pod > fmax.man
