#!/bin/sh

PRGNAM=toxic
VERSION=${VERSION:-0.7.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_sbolokanov}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/sbolokanov}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP

if [ "$VERSION" = "master" ]; then
  rm -rf toxcore
  git clone https://github.com/irungentoo/toxcore.git
  cd toxcore
  GIT_VERSION=$(git describe --tags --always)
else
  rm -rf $PRGNAM-$VERSION
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
  cd $PRGNAM-$VERSION
fi

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

#./autogen.sh
#CFLAGS="$SLKCFLAGS" \
#./configure \
#  --prefix=/usr \
#  --libdir=/usr/lib${LIBDIRSUFFIX} \
#  --docdir=/usr/doc/$PRGNAM-$VERSION \
#  --disable-static \
#  --build=$ARCH-slackware-linux

make PREFIX="/usr"
make install DESTDIR=$PKG PREFIX="/usr"

#AUTHORS ChangeLog NEWS
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a COPYING INSTALL* README* \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/slack-required > $PKG/install/slack-required

cd $PKG
if [ "$VERSION" = "master" ]; then
  /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-git_$GIT_VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
else
  /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
fi
